### PR TITLE
add private channel

### PR DESCRIPTION
**Pull request by ykris45**
see our internal channel, and jiggytom aka Mr Thomas tryed to type !tip and it cant work on this channel. i think it can help the issues

### CODE REVIEW

**Comment by nikooo777** [comment]
hey @ykris45 this will not work unless you use that variable. Can you solve this yourself or do you need help with that?

**Comment by ykris45** [comment]
hey @nikooo777 yes i need help with that sir?. and can you help me to solve it.

**Comment by tzarebczan** [comment]
Looks like this is only half finished. You grabbed the channel but don't check it with the whitelist.

**Comment by ykris45** [comment]
@tzarebczan how to check it with the whitelist?. can you help me. so all team can use this channel..

**Comment by ceoger** [comment]
Do we have to add the channel id to the tipbot white list? not sure if it works the same way like the wunderbot @filipnyquist

**Comment by filipnyquist** [comment]
@ceoger exactly, it needs to be added to the whitelist. It also seems that the bot only supports one channel as of now in the code.

**Comment by tzarebczan** [comment]
Going to close this for now, someone can pick it up later if you feel strongly about it.

**Pull request closed without merging**
