### PR TITLE
add message to send DM to tipbot

### PR DESCRIPTION
**Pull request by MSFTserver**

### CODE REVIEW

**Review by kauffj — CHANGES_REQUESTED** [review]
Be sure to follow @lyoshenka's coding maxims (https://gist.github.com/lyoshenka/0a43205aa9a072b196ff87e2c689a8b9) and DRY!

(Aka make _at least_ that number, if not the message and/or check itself, a shared value or piece of logic.

**Comment by MSFTserver** [comment]
@kauffj theres is  alot of repeated code throughout the bot i tried to clean it up one time but got told that it was suppose to be like that and they didnt want be setting variables to stuff so we dont have to repeat an api url 20 times in price bot and other things........
image

**Comment by MSFTserver** [comment]
id be much happier not repeating ourselves to

**Comment by MSFTserver** [comment]
@kauffj hows this now or did you have other things in mind of fixes

**Comment by nikooo777** [comment]
i'm closing this PR as it's obsolete at this point

**Pull request closed without merging**
